### ISSUE TITLE
On lists of pages, SummaryCards go wild

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SummaryCards#7]
### Setup and configuration
- SUC version: 1.0.0-alpha (73aeb05)
- MW version: 1.27.1
- DB (MySQL etc.): PHP  5.5.38 (cgi-fcgi)  MySQL    5.5.52-cll
### Issue

Occasionally I can experience that summary cards "go wild" (see screenshot). Interstingly, this happened only if the lists of pages are inside HeaderTabs. Ans it disappears after a while. I tested to remove the headertabs call, which worked. But after putting it in again, it worked also inside headertabs!?!
![suc-problem](https://cloud.githubusercontent.com/assets/4318745/19152615/214f28d4-8bd3-11e6-8782-4734c3afb6c7.jpg)
Happend both in Firefox and Chrome.

**Comment by krabina** [comment]
it has nothing to do with headertabs at all. it just happened on regular pages without headertabs as well. it probably is some kind of caching problem or overload when too many links exist on one page?

**Comment by kghbln** [comment]
Indeed this is unrelated to the header tabs used. Thanks for reporting. I have the suspicion that it takes to long to render the summery card and if someone "frantically" hovers over all the links ...

**Comment by mwjames** [comment]
> I can experience that summary cards "go wild" (see screenshot). 

The issue is caused by an empty content container such as:

![image](https://cloud.githubusercontent.com/assets/1245473/19161320/9f17574e-8bf3-11e6-87e4-2f9d6027d6cc.png)

> it probably is some kind of caching problem or overload when too many links exist on one page?

On a local instance, I'm unable to observe this issue and to understand the potential root cause it would be helpful if you could replace [0] with the content found in [0.r] (adds extra log output, requires a hard rest [1] of the browser cache in order to load the changed code):

After [0.r] and when `$GLOBALS['sucgTooltipRequestCacheLifetime'] = 0;` is changed what is the output of the console log before and after that change when hovering a link? 

Example output (with [0.r]):

![image](https://cloud.githubusercontent.com/assets/1245473/19162115/dfa7d59c-8bf6-11e6-843a-f62836144e8d.png)

In case of `$GLOBALS['sucgTooltipRequestCacheLifetime'] = 0;` each time you hover a legitimate link [2], your browser should call the API and show something like:

![image](https://cloud.githubusercontent.com/assets/1245473/19159314/3a80d76c-8bec-11e6-9ce1-171fcb8df22c.png)

[0] https://github.com/SemanticMediaWiki/SummaryCards/blob/master/res/ext.summaryCards.js
[0.r] https://gist.github.com/mwjames/177b924745eb6b4892979bb4704026fc

[1] http://refreshyourcache.com/en/cache/
[2] https://github.com/SemanticMediaWiki/SummaryCards/blob/master/docs/01-content-summaries.md#legitimate-links

**Comment by krabina** [comment]
here is what I did:
1) tried to reproduce the error without any changes and an open console. I was NOT able to reproduce the problem. I the console it said:
"Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil!"

2) I tried [0.r] with ctr+f5 to clear the cache. Now the problem showed up again, but the same message in the console.

3) set $GLOBALS['sucgTooltipRequestCacheLifetime'] = 0;
no difference. same as 2): problem exists, same message in console

4) changed back to [0] again, removed $GLOBALS['sucgTooltipRequestCacheLifetime'] = 0;
result: everything works again, I am not able to reproduce the problem !?!

**Comment by kghbln** [comment]
Strange. I cannot longer reproduce this issue when browsing sandbox. Since SummaryCards and the browser used Fx 49 have not changed since the only difference is now that sandbox is on MW 1.28 rather than on MW 1.27 as it used to be. @krabina New observations on your end?

**Comment by kghbln** [comment]
I assume that this issue no longer appears in current versions of SummaryCards as well as browsers. Please reopen if I am wrong about this.
